// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBRNg_wIpZIKYH0S0z99SGXVXZYL3IvC4',
    appId: '1:592077403906:web:4cd6fa37e6f0ad8cf3741b',
    messagingSenderId: '592077403906',
    projectId: 'projectcordial-596bd',
    authDomain: 'projectcordial-596bd.firebaseapp.com',
    storageBucket: 'projectcordial-596bd.firebasestorage.app',
    measurementId: 'G-5JYMJ10765',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALQmvHsWtSFgk79UPFEYzh99XKWTV7rE8',
    appId: '1:592077403906:android:91d790f1463d62b7f3741b',
    messagingSenderId: '592077403906',
    projectId: 'projectcordial-596bd',
    storageBucket: 'projectcordial-596bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzjrhItJE2KHWS9xKS_MyhR4cQEyqedw',
    appId: '1:592077403906:ios:b26c51a38fdc6c5cf3741b',
    messagingSenderId: '592077403906',
    projectId: 'projectcordial-596bd',
    storageBucket: 'projectcordial-596bd.firebasestorage.app',
    iosClientId: '592077403906-q56o4a4cmkt7i0kk2r0fk5nugfe2tdak.apps.googleusercontent.com',
    iosBundleId: 'ruten.cordial.cordial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzjrhItJE2KHWS9xKS_MyhR4cQEyqedw',
    appId: '1:592077403906:ios:b26c51a38fdc6c5cf3741b',
    messagingSenderId: '592077403906',
    projectId: 'projectcordial-596bd',
    storageBucket: 'projectcordial-596bd.firebasestorage.app',
    iosClientId: '592077403906-q56o4a4cmkt7i0kk2r0fk5nugfe2tdak.apps.googleusercontent.com',
    iosBundleId: 'ruten.cordial.cordial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBRNg_wIpZIKYH0S0z99SGXVXZYL3IvC4',
    appId: '1:592077403906:web:5651d4620df9735cf3741b',
    messagingSenderId: '592077403906',
    projectId: 'projectcordial-596bd',
    authDomain: 'projectcordial-596bd.firebaseapp.com',
    storageBucket: 'projectcordial-596bd.firebasestorage.app',
    measurementId: 'G-HPHRD54MBY',
  );
}
